# Generated by Django 4.1.6 on 2023-02-06 08:01

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=store.models.get_file_path
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0=default,1=hidden"),
                ),
                (
                    "release",
                    models.BooleanField(default=False, help_text="0=default,1=Release"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=150)),
                (
                    "movie_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=store.models.get_file_path
                    ),
                ),
                ("producer", models.CharField(max_length=150)),
                ("actor", models.CharField(max_length=500)),
                ("small_description", models.CharField(max_length=500)),
                ("quantity", models.IntegerField()),
                ("description", models.TextField(max_length=500)),
                ("original_price", models.FloatField()),
                ("selling_price", models.FloatField()),
                ("scedule_date", models.DateField(blank=True)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0=default,1=hidden"),
                ),
                (
                    "release",
                    models.BooleanField(default=False, help_text="0=default,1=Release"),
                ),
                ("tag", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.category"
                    ),
                ),
            ],
        ),
    ]
